<?php

namespace EcommerceBundle\Repository;

/**
 * lignecommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class lignecommandeRepository extends \Doctrine\ORM\EntityRepository
{
}
