ecommerce_homepage:
    path:     /home
    defaults: { _controller: EcommerceBundle:Default:home }

dashboard_admin:
    path:     /admin/dashboard
    defaults: { _controller: EcommerceBundle:Default:dashboard }

Produit_consulter:
    path:     /produit/consulter
    defaults: { _controller: EcommerceBundle:Produit:consulter }

Categorie_list_dashboard:
    path:     /admin/dashboard/categorie/afficher
    defaults: { _controller: EcommerceBundle:Categorie:afficher }

supprimer_categorie_dashboard:
    path:     /admin/dashboard/categorie/supprimer
    defaults: { _controller: EcommerceBundle:Categorie:supprimer }

Categorie_goajouter_dashboard:
    path:     /admin/dashboard/categorie/goajouter
    defaults: { _controller: EcommerceBundle:Categorie:goajouter }

Categorie_ajouter_dashboard:
    path:     /admin/dashboard/categorie/ajouter
    defaults: { _controller: EcommerceBundle:Categorie:ajouter }

Categorie_goupdate_dashboard:
    path:     /admin/dashboard/categorie/goupdate
    defaults: { _controller: EcommerceBundle:Categorie:goupdate }

Categorie_update_dashboard:
    path:     /admin/dashboard/categorie/update
    defaults: { _controller: EcommerceBundle:Categorie:update }



Fournisseur_list_dashboard:
    path:     /admin/dashboard/fournisseur/afficher
    defaults: { _controller: EcommerceBundle:Fournisseur:afficher }

supprimer_fournisseur_dashboard:
    path:     /admin/dashboard/fournisseur/supprimer
    defaults: { _controller: EcommerceBundle:Fournisseur:supprimer }

Fournisseur_goajouter_dashboard:
    path:     /admin/dashboard/fournisseur/goajouter
    defaults: { _controller: EcommerceBundle:Fournisseur:goajouter }

Fournisseur_ajouter_dashboard:
    path:     /admin/dashboard/fournisseur/ajouter
    defaults: { _controller: EcommerceBundle:Fournisseur:ajouter }

Fournisseur_goupdate_dashboard:
    path:     /admin/dashboard/fournisseur/goupdate
    defaults: { _controller: EcommerceBundle:Fournisseur:goupdate }

Fournisseur_update_dashboard:
    path:     /admin/dashboard/fournisseur/update
    defaults: { _controller: EcommerceBundle:Fournisseur:update }



Produit_list_dashboard:
    path:     /admin/dashboard/produit/afficher
    defaults: { _controller: EcommerceBundle:Produit:afficher }

supprimer_produit_dashboard:
    path:     /admin/dashboard/produit/supprimer
    defaults: { _controller: EcommerceBundle:Produit:supprimer }

Produit_goajouter_dashboard:
    path:     /admin/dashboard/produit/goajouter
    defaults: { _controller: EcommerceBundle:Produit:goajouter }

Produit_ajouter_dashboard:
    path:     /admin/dashboard/produit/ajouter
    defaults: { _controller: EcommerceBundle:Produit:ajouter }

Produit_goupdate_dashboard:
    path:     /admin/dashboard/produit/goupdate
    defaults: { _controller: EcommerceBundle:Produit:goupdate }

Produit_update_dashboard:
    path:     /admin/dashboard/produit/update
    defaults: { _controller: EcommerceBundle:Produit:update }

Produit_list_front:
    path:     /shop
    defaults: { _controller: EcommerceBundle:Produit:afficherFront }

Avis_ajouter:
    path:     /avis/ajouter
    defaults: { _controller: EcommerceBundle:Avis:ajouter }

Panier_ajouter:
    path:     /panier/ajouter
    defaults: { _controller: EcommerceBundle:Panier:ajouter }

Panier_afficher:
    path:     /panier/afficher
    defaults: { _controller: EcommerceBundle:Panier:afficher }

Panier_supprimer:
    path:     /panier/supprimer
    defaults: { _controller: EcommerceBundle:Panier:supprimer }

Panier_update:
    path:     /panier/update
    defaults: { _controller: EcommerceBundle:Panier:update }

Favorie_ajouter:
    path:     /favorie/ajouter
    defaults: { _controller: EcommerceBundle:Favorie:ajouter }

Favorie_afficher:
    path:     /favorie/afficher
    defaults: { _controller: EcommerceBundle:Favorie:afficher }

Favorie_supprimer:
    path:     /favorie/supprimer
    defaults: { _controller: EcommerceBundle:Favorie:supprimer }

notification_user:
    path:     /notification/user
    defaults: { _controller: EcommerceBundle:Notification:list }
    methods: [POST]

Notification_supprimer:
    path:     /admin/dashboard/notification/supprimer
    defaults: { _controller: EcommerceBundle:Notification:supprimer }

user_update:
    path:     /user/modifier
    defaults: { _controller: AppBundle:User:update }

user_goupdate:
    path:     /user/gomodifier
    defaults: { _controller: AppBundle:User:goupdate }

user_consulter:
    path:     /user/consulter
    defaults: { _controller: AppBundle:User:consulter }


Admin_dashboard_statique:
    path:     /admin/dashboard/statique
    defaults: { _controller: EcommerceBundle:Produit:statique }

Commande_list_dashboard:
    path:     /admin/dashboard/commandes/afficher
    defaults: { _controller: EcommerceBundle:Commandes:afficher }

Commande_changer_etat_dashboard:
    path:     /admin/dashboard/commandes/etat/changer
    defaults: { _controller: EcommerceBundle:Commandes:changeretat }

Commande_consulter_dashboard:
    path:     /admin/dashboard/commandes/consulter
    defaults: { _controller: EcommerceBundle:Commandes:consulter }

Commande_ajouter:
    path:     /commandes/ajouter
    defaults: { _controller: EcommerceBundle:Commandes:ajouter }

LigneCommande_supprimer:
    path:     /lignecommandes/supprimer
    defaults: { _controller: EcommerceBundle:Commandes:supprimer }

My_Commande_list_home:
    path:     /commandes/afficher
    defaults: { _controller: EcommerceBundle:Commandes:affichermy }

Commande_consulter_home:
    path:     /commandes/consulter
    defaults: { _controller: EcommerceBundle:Commandes:monlistconsulter }

LigneCommande_update_quantite_home:
    path:     /commandes/ligne/update
    defaults: { _controller: EcommerceBundle:Commandes:updateligne }














